/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorActividad;
import controlador.ControladorAgenda;
import controlador.ControladorTarea;
import controlador.ControladorUsuario;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Actividad;
import modelo.Agenda;
import modelo.Tarea;
import modelo.Usuario;

/**
 *
 * @author ADRIANA
 */
public class VentanaAgenda extends javax.swing.JInternalFrame {

    private ControladorActividad controladorActividad;
    private ControladorAgenda controladorAgenda;
    private ControladorUsuario controladorUsuario;
    private ControladorTarea controladorTarea;
    DefaultTableModel model1;
    private List<Agenda> listaAgenda;

    /**
     * Creates new form VentanaAgenda
     */
    public VentanaAgenda() {
        initComponents();
        controladorActividad = new ControladorActividad();
        controladorAgenda = new ControladorAgenda();
        controladorTarea = new ControladorTarea();
        controladorUsuario = new ControladorUsuario();
        limpiar();
        llenarActividad(cbxActividad);
        llenarTarea(cbxTarea);
        llenarUsuario(cbxUsuario);

        lista();

    }

    public void limpiar() {
        cbxActividad.removeAllItems();
        cbxTarea.removeAllItems();
        cbxUsuario.removeAllItems();
    }

    public void llenarActividad(JComboBox combo) {
        controladorActividad = new ControladorActividad();
        List<Actividad> lista = controladorActividad.listar();
        combo.addItem("Seleccionar Actividad");
        for (Actividad actividad : lista) {
            combo.addItem(actividad.getNombre());
        }
    }

    public void llenarTarea(JComboBox combo) {
        controladorTarea = new ControladorTarea();
        List<Tarea> lista = controladorTarea.listar();
        combo.addItem("Seleccionar Tarea");
        for (Tarea tarea : lista) {
            combo.addItem(tarea.getNombre());
        }
    }

    public void llenarUsuario(JComboBox combo) {
        controladorUsuario = new ControladorUsuario();
        List<Usuario> lista = controladorUsuario.listar();
        combo.addItem("Seleccionar Usuario");
        for (Usuario usuario : lista) {
            combo.addItem(usuario.getNombre() + " " + usuario.getApellido());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgenda = new javax.swing.JTable();
        btnCrear = new javax.swing.JToggleButton();
        btnEliminar = new javax.swing.JToggleButton();
        cbxUsuario = new javax.swing.JComboBox<>();
        cbxTarea = new javax.swing.JComboBox<>();
        cbxActividad = new javax.swing.JComboBox<>();
        btnRefrescar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tblAgenda.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        tblAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAgendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAgenda);

        btnCrear.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        cbxUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxUsuarioActionPerformed(evt);
            }
        });

        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxTarea, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxUsuario, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxActividad, javax.swing.GroupLayout.Alignment.TRAILING, 0, 127, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefrescar)
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefrescar))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void lista() {
        model1 = new DefaultTableModel();
        model1.addColumn("ID");
        model1.addColumn("USUARIO");
        model1.addColumn("ACTIVIDAD");
        model1.addColumn("TAREA");
        listaAgenda = controladorAgenda.listar();
        for (Agenda agenda : listaAgenda) {
            Object[] datos = new Object[1000];
            datos[0] = agenda.getId();
            datos[1] = agenda.getUsuario().getNombre() + " " + agenda.getUsuario().getApellido();
            datos[2] = agenda.getActividad().getNombre();
            datos[3] = agenda.getTarea().getNombre();
            model1.addRow(datos);
        }
        tblAgenda.setModel(model1);
        tblAgenda.getColumnModel().getColumn(0).setMaxWidth(0);
        tblAgenda.getColumnModel().getColumn(0).setMinWidth(0);
        tblAgenda.getColumnModel().getColumn(0).setPreferredWidth(0);

    }

    private void tblAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAgendaMouseClicked
//        limpiar();
//        int filaSeleccionada = tblAgenda.getSelectedRow();
//        String codigo = tblAgenda.getValueAt(filaSeleccionada, 0).toString();
//        int id = Integer.valueOf(codigo);
//        buscarActividadTabla(id);
    }//GEN-LAST:event_tblAgendaMouseClicked

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        Agenda agenda = new Agenda();
        String usuario = cbxUsuario.getSelectedItem().toString();
        String[] n = usuario.split(" ");
        String nombre = n[0];
        String apellido = n[1];
        String actividad = cbxActividad.getSelectedItem().toString();
        String tarea = cbxTarea.getSelectedItem().toString();

        Actividad a = controladorActividad.buscarActividadNombre(actividad);
        Tarea t = controladorTarea.buscarTareaNombre(tarea);
        Usuario u = controladorUsuario.buscarUsuarioNombre(nombre, apellido);
        agenda.setActividad(a);
        agenda.setTarea(t);
        agenda.setUsuario(u);
        if (controladorAgenda.crearAgenda(agenda) == true) {
            JOptionPane.showMessageDialog(null, "Ingresado correctamnte");
        } else {
            JOptionPane.showMessageDialog(null, "No fue ingresado");
        }
        limpiar();
        llenarActividad(cbxActividad);
        llenarTarea(cbxTarea);
        llenarUsuario(cbxUsuario);
        lista();

    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tblAgenda.getSelectedRow();
        String codigo = tblAgenda.getValueAt(filaSeleccionada, 0).toString();
        int id = Integer.valueOf(codigo);
        controladorAgenda.eliminarAgenda(id);
        limpiar();
        llenarActividad(cbxActividad);
        llenarTarea(cbxTarea);
        llenarUsuario(cbxUsuario);
        lista();

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cbxUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxUsuarioActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        // TODO add your handling code here:
        limpiar();
        llenarActividad(cbxActividad);
        llenarTarea(cbxTarea);
        llenarUsuario(cbxUsuario);
        lista();
    }//GEN-LAST:event_btnRefrescarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCrear;
    private javax.swing.JToggleButton btnEliminar;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JComboBox<String> cbxActividad;
    private javax.swing.JComboBox<String> cbxTarea;
    private javax.swing.JComboBox<String> cbxUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAgenda;
    // End of variables declaration//GEN-END:variables
}
